//products.js
export let products=[
    {
        id:1,
        name:"mobile",
        brand:"apple",
        category:"electronics",
        price:50000,
        rating:2,
        instock:true,
        comments:["good","great","super"]
    },
    {
        id:2,
        name:"latop",
        brand:"Dell",
        price:60000,
        category:"electronics",
        rating:4.0,
        instock:true,
        comments:["good","average","Great"],
        
    },
    {
        id:3,
        name:"chair",
        brand:"wakefit",
        price:5000,
        category:"furniture",
        rating:4,
        instock:false,
        comments:["good","super"]
    },
    {
        id:4,
        name:"mobile",
        brand:"apple",
        category:"electronics",
        price:50000,
        rating:4.5,
        instock:true,
        comments:["good","great","super"]
    },
    {
        id:5,
        name:"latop",
        brand:"Dell",
        price:60000,
        category:"electronics",
        rating:4.0,
        instock:true,
        comments:["good","average","Great"],
        
    },
    {
        id:6,
        name:"chair",
        brand:"wakefit",
        price:5000,
        category:"furniture",
        rating:4,
        instock:false,
        comments:["good","super"]
    },
    {
        id:7,
        name:"mobile",
        brand:"apple",
        category:"electronics",
        price:50000,
        rating:4.5,
        instock:true,
        comments:["good","great","super"]
    },
    {
        id:8,
        name:"latop",
        brand:"Dell",
        price:60000,
        category:"electronics",
        rating:4.0,
        instock:true,
        comments:["good","average","Great"],
        
    },
    {
        id:9,
        name:"chair",
        brand:"wakefit",
        price:5000,
        category:"furniture",
        rating:4,
        instock:false,
        comments:["good","super"]
    },
    {
        id:10,
        name:"mobile",
        brand:"apple",
        category:"electronics",
        price:50000,
        rating:4.5,
        instock:true,
        comments:["good","great","super"]
    },
    {
        id:12,
        name:"latop",
        brand:"Dell",
        price:60000,
        category:"electronics",
        rating:4.0,
        instock:true,
        comments:["good","average","Great"],
        
    },
    {
        id:13,
        name:"chair",
        brand:"wakefit",
        price:5000,
        category:"furniture",
        rating:4,
        instock:false,
        comments:["good","super"]
    },
    {
        id:14,
        name:"mobile",
        brand:"apple",
        category:"electronics",
        price:50000,
        rating:4.5,
        instock:true,
        comments:["good","great","super"]
    },
    {
        id:15,
        name:"latop",
        brand:"Dell",
        price:60000,
        category:"electronics",
        rating:4.0,
        instock:true,
        comments:["good","average","Great"],
        
    },
    {
        id:16,
        name:"chair",
        brand:"wakefit",
        price:5000,
        category:"furniture",
        rating:4,
        instock:false,
        comments:["good","super"]
    },
    {
        id:17,
        name:"mobile",
        brand:"apple",
        category:"electronics",
        price:50000,
        rating:4.5,
        instock:true,
        comments:["good","great","super"]
    },
    {
        id:18,
        name:"latop",
        brand:"Dell",
        price:60000,
        category:"electronics",
        rating:4.0,
        instock:true,
        comments:["good","average","Great"],
        
    },
    {
        id:19,
        name:"chair",
        brand:"wakefit",
        price:5000,
        category:"furniture",
        rating:4,
        instock:false,
        comments:["good","super"]
    }
]